exp_name: 'clip_finetune'
outdir: './experiments'

num_gpu: 1
gpu_id: 0

seed: 42

dataset:
    root: './dataset/shopee-product-matching/'
    path_to_folds: './dataset/shopee-product-matching/folds.csv'
    num_of_classes: 11014
    input_size: 224
    batch_size: 32
    num_workers: 16


image_model:
    model_name: 'eca_nfnet_l1'
    pretrained: True
    use_fc: False
    fc_dim: 512
    dropout: 0.
    loss_module: 'softmax'


text_model:
    'model_name': 'cahya/bert-base-indonesian-522M'
    'use_fc': False
    'fc_dim': 512
    'dropout': 0.
    loss_module: 'softmax'

multi:
    'use_fc': True
    'fc_dim': 1920
    'dropout': 0.
    loss_module: 'arcface'

clip:
    'model_name': "ViT-B/32"
    loss_module: 'arcface'

head:
    "s": 30.0
    "margin": 0.50
    "ls_eps": 0.0
    "theta_zero": 0.785

train:
    full_training: True # Train on full data without validation
    debug: False
    warmup: False
    optimizer:
        name: 'AdamW'
        learning_rate: 0.00001
        momentum: 0.9
        weight_decay: 0.0001
    lr_scheduler:
        name: 'MultiStepLR'
        step_size: 9
        milestones: [50, 80]
        eta_min: 0.0001
        T_max: 4
        gamma: 0.1
        factor: 0.1
        patience: 10
    n_epochs: 200
    label_smoothing: false
    eps: 0.01
    freq_vis: 200